<?php
/**
 * Copyright © Elogic. All rights reserved.
 * See https://elogic.co for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 * @var $_hiddenPriceHelper \Elogic\HidePrice\Helper\Data
 */
?>
<?php $_helper = $this->helper(Magento\Catalog\Helper\Output::class); ?>
<?php $_hiddenPriceHelper = $this->helper(Elogic\HidePrice\Helper\Data::class); ?>
<?php $_product = $block->getProduct(); ?>
<div class="product-add-form">
    <?php if (!$_hiddenPriceHelper->isPriceHidden($_product)):?>
    <form data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
          action="<?= $block->escapeUrl($block->getSubmitUrl($_product)) ?>" method="post"
          id="product_addtocart_form"<?php if ($_product->getOptions()) :?> enctype="multipart/form-data" <?php endif; ?>
          data-product-availability="<?php echo $one = ($_product->isAvailable()) ? 'in_stock' : 'out_of_stock'?>">
        <input type="hidden" name="product" value="<?= (int)$_product->getId() ?>" />
        <input type="hidden" name="selected_configurable_option" value="" />
        <input type="hidden" name="related_product" id="related-products-field" value="" />
        <input type="hidden" name="item"  value="<?= (int)$block->getRequest()->getParam('id') ?>" />
        <?= $block->getBlockHtml('formkey') ?>
        <?= $block->getChildHtml('form_top') ?>
        <?php if (!$block->hasOptions()) :?>
            <?= $block->getChildHtml('product_info_form_content') ?>
        <?php else :?>
            <?php if ($_product->isSaleable() && $block->getOptionsContainer() == 'container1') :?>
                <?= $block->getChildChildHtml('options_container') ?>
            <?php endif;?>
        <?php endif; ?>

        <?php if ($_product->isSaleable() && $block->hasOptions() && $block->getOptionsContainer() == 'container2') :?>
            <?= $block->getChildChildHtml('options_container') ?>
        <?php endif;?>
        <?= $block->getChildHtml('form_bottom') ?>
    </form>
    <?php endif;?>
    <div class="modal"></div>
    <button class="ask-for-more-information-button" lang=""><?= $block->escapeHtml(__('Request a Quote')) ?></button>
    <div class="ask-for-more-information-popup" style="display: none">
        <div class="popup-wrap">
            <div class="ask-for-more-information-content">
                <span class="ask-for-more-information-title"><?php echo __('CONTACT US') ?></span>
                <span class="ask-for-more-information-popup-close">&times;</span>
                <div class="ask-for-more-information-popup-content"><?php echo __('If you would like to know more about this product, send us a message here. You can also contact our ') ?>
                    <a href="/yhteystiedot" target="_blank" rel="noopener noreferrer"><?= $block->escapeHtml(__('experts.')) ?></a>
                </div>
            </div>
            <form id="ask-for-more-form" class="ask-for-more-information-form information_menu_form" name="ask_for_more_information_form" action="/askformoreinformation/index/email" data-mage-init='{"validation": {}}'>
                <?= $block->getBlockHtml('formkey') ?>
                <input class="formName" name="name" type="text" autocomplete="off" placeholder="<?php echo __('Name') ?>">
                <input class="formName" name="company" type="text" autocomplete="off" placeholder="<?php echo __('Company') ?>">
                <input class="formMenuemail" name="menuemail" type="text" autocomplete="off" placeholder="<?php echo __('Email') ?>" data-validate="{required:true, 'validate-email':true}">
                <input type="text" title="Telephone" class="formTelephone" name="telephone" autocomplete="off" placeholder="<?php echo __('Phone') ?>" data-validate="{required:true, 'validate-number':true}">
                <textarea class="formComment" name="comment" placeholder="<?php echo __('Write your message here') ?>"></textarea>
                <input type="text" style="display:none !important;" value="<?php echo $_product->getSku() ?>"  name="product_sku">
                <input type="text" style="display:none !important;" value="<?php echo $_product->getName() ?>" name="product_name">
                <input type="reset" class="configreset" value="<?= $block->escapeHtml(__('Clear')) ?>">
                <input id="ask-for-more-submit" class="ask-for-more-information-form-submit" type="submit" value="<?php echo __('Send') ?>">
            </form>
        </div>
    </div>
</div>
<script src="<?php echo $block->getViewFileUrl('Elogic_AskForMoreInformation::js/popup.js')?>"></script>
<script type="text/x-magento-init">
    {
        "[data-role=priceBox][data-price-box=product-id-<?= $block->escapeHtml($_product->getId()) ?>]": {
            "priceBox": {
                "priceConfig":  <?= /* @noEscape */ $block->getJsonConfig() ?>
            },
            "askForMoreSubmit": {}
        }
    }
</script>
