<button type="button" class="btn btn-primary" id="questionButton"><?php echo __('Ask Question')?></button>

<div class="modal" id="productQuestion" >

<div style="display: none">
            <form method="post" class="formq" id="formq" name="formq" action="<?= $escaper->escapeUrl($block->getUrl('product/email/question'))?>">

                            <label for="name"><?php echo __('Name');?>:</label>
                            <input type="text" class="form-control" id="name" placeholder="<?php echo __('Enter name')?>" name="name">


                            <label for="question"><?php echo __('Question') ?> :</label>
                            <input type="text" name="question" id="question" placeholder="Ask your question here..." />

                <button type="submit" class="submitQuestion">Send</button>
            </form>
</div>
    <form method="post" class="formq" id="formq" name="formq" action="<?= $escaper->escapeUrl($block->getUrl('product/email/question'))?>">
        <fieldset class="fieldset">
            <div class="form-group">
                <label for="name"><?php echo __('Name');?>:</label>
                <input type="email" class="form-control" id="name" placeholder="<?php echo __('Enter name')?>" name="name">
            </div>
            <div class="form-group">
                <label for="question"><?php echo __('Question') ?> :</label>
                <input type="text" name="question" id="question" placeholder="Ask your question here..." />
            </div>

            <button type="submit" class="submitQuestion" value="">Send</button>

        </fieldset>
    </form>
</div>


<script type="text/x-magento-init">
    {
        "*": {
            "productQuestionComponent" : {}
        }
    }
</script>
