<div data-bind="scope: 'custom'">
    <!-- ko template: getTemplate() --><!--/ko-->
</div>
<script type="text/x-magento-init">
   {
       "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "custom": {
                        "component": "Magento_Theme/js/view/custom",
                        "text": "text from phtml"
                    }
                }
            }
       }
   }
</script>


<!---->
<!--"template": "Magento_Theme/custom" -  можна вказувати і тут і це буде мати більший пріоритет, ніж у custom.js-->
