<div data-bind="scope: 'custom'">
<!--    <span data-bind="text: text"></span>-->
<!--    <span data-bind="text2: text2"></span>-->
<!--    <span data-bind="i18n: 'text has to be translated'"></span>-->
<!--    <span data-bind="text: $t('text has %1 to be translated').replace(%1, customVar)"></span>-->
    <button data-bind="click: toggleState">Toggle state</button>
    <!-- ko if: isActive -->
    <div data-bind="mageInit: { 'Magento_Theme/js/script':{} }">is active</div>
    <!-- /ko -->
</div>
<script type="text/x-magento-init">
   {
       "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "custom": {
                        "component": "Magento_Theme/js/view/custom"
                    }
                }
            }
       }
   }
</script>
